# Generated by Django 4.2.23 on 2025-08-15 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game_scores',
            options={'ordering': ['-score'], 'verbose_name': 'Game Score', 'verbose_name_plural': 'Game Scores'},
        ),
    ]
