# Generated by Django 4.2.23 on 2025-08-18 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon2', '0003_gamerprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GamerProfile',
        ),
    ]
